use_frameworks!
platform :ios, '9.3'

target 'FlatPaymentMethod_Example' do
    pod 'FlatPaymentMethod', :path => '../'
    pod 'PaymentValidator', '~> 0.0.3'
    pod 'FlatCreditCard', '~> 0.0.3'
    
    target 'FlatPaymentMethod_Tests' do
        inherit! :search_paths
        
    end
end

post_install do |installer|
    installer.pods_project.build_configurations.each do |config|
        config.build_settings.delete('CODE_SIGNING_ALLOWED')
        config.build_settings.delete('CODE_SIGNING_REQUIRED')
    end
end

